# GitHub Pages Configuration for The Book of Joa
title: "The Book of Joa - Ultimate Open Source Religion"
description: "The world's first completely violence-free, exploitation-free, equality-absolute spiritual wisdom system. Made by humans, for humans."
url: "https://bookofjoa.github.io"
baseurl: "/bookofjoa"

# Build settings
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: assets/css
  style: compressed

# Collections
collections:
  chapters:
    output: true
    permalink: /:collection/:name/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# SEO
author: "Book of Joa Contributors"
twitter:
  username: bookofjoa
facebook:
  app_id: 
  publisher: 
  admins: 

# Social links
social:
  name: The Book of Joa
  links:
    - https://github.com/bookofjoa/bookofjoa

# Default front matter
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      author: "Book of Joa Contributors"
  - scope:
      path: ""
      type: "chapters"
    values:
      layout: "default"
      author: "Book of Joa Contributors"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE
  - .gitignore
  - userinput.py

# Include
include:
  - _pages
  - assets

# GitHub Pages specific
github: [metadata]
kramdown:
  input: GFM
  hard_wrap: false

# Security
safe: true
incremental: false
lsi: false
highlighter: rouge
gist:
  noscript: false

# Performance
liquid:
  error_mode: warn
  strict_filters: false
  strict_variables: false